### ISSUE TITLE
171129 컴파일 및 실행 보고

### ISSUE THREAD

**Issue by kimhono97** [GradeScholarship/hangman#1]
## 환경
 - OS : Windows 10 64bit
 - Compiler : Eclipse Oxygen.1a Release (4.7.1a)

## 실행 결과
 - 성공

## 내용 보고
 1. Console 기반 프로그램인 것을 확인
 2. java파일 1개로 구성된 아주 간단한 프로그램임
 3. Hangman Rule을 무시함 (aeiou Guesss가능 + 도중에 Word Guess불가)

## 추가 아이디어
 1. 본래의 Hangman Rule를 적용해야 할 것 같다.
 2. 디자인을 좀 더 화려하게하면 좋을 것 같다.

**Comment by dovigod** [comment]
./gradlew chrome 써서 테스트 진행해봤어? test failed 뜨는데 ㅜ

**Comment by go1217jo** [comment]
<h3> 혹시나 해서 .class 파일에서 .java 파일 추출하는 방법 올립니다. </h3>
http://delirussum.tistory.com/entry/ETC-%EC%9E%90%EB%B0%94-%ED%81%B4%EB%9E%98%EC%8A%A4-%EB%94%94%EC%BB%B4%ED%8C%8C%EC%9D%BC%EB%9F%ACDecompiler-JAD%EC%99%80-JadClipse%EC%9D%98-%ED%99%9C%EC%9A%A9
