### ISSUE TITLE
GUI 구현

### ISSUE THREAD

**Issue by go1217jo** [GradeScholarship/hangman#2]
java swing을 이용해서 기본적인 GUI를 구현하면 좋을 것 같다.

**Comment by go1217jo** [comment]
![image](https://user-images.githubusercontent.com/30193942/33382041-061dbf0a-d563-11e7-9e0e-9c70905df14f.png)
기본적인 프레임 구현 (GUI branch)

**Comment by JeanGyuHu** [comment]
GUI로 구현하기 위해서 시작창 만들어 봤습니다.
![hangmanstart](https://user-images.githubusercontent.com/32431385/33481420-bc7ddb3e-d6d7-11e7-92b6-7c1a74acfe6a.PNG)

**Comment by go1217jo** [comment]
StartFrame에서 new Main(System.in, System.out, 5).exec(); 을 호출해주셔야 합니다.

**Comment by JeanGyuHu** [comment]
합쳐보도록 하겠습니다.

**Comment by go1217jo** [comment]
클래스로 분리가 필요할 것 같습니다
혹시 @JeanGyuHu 님이 틀을 구성해주실 수 있는지요?

**Comment by go1217jo** [comment]
제가 원래 exec 함수를 이벤트로 옮겨보겠습니다.

**Comment by JeanGyuHu** [comment]
제가 전체적인 틀을 구성할테니 @go1217jo 님이 기존에 있던 코드 전체적인 기능을 JPanel에서 구동하게 만들어주세요

**Comment by go1217jo** [comment]
네 알겠습니다.

**Comment by go1217jo** [comment]
그럼 KeyAnswer 클래스에 전부 담도록 하겠습니다.

**Comment by JeanGyuHu** [comment]
네 master에 그냥 commit 하시면 될 것 같고 저는 branch해서 틀 만들어 나가겠습니다 완성한 후에 합치는걸로 하는게 어떨까요?

**Comment by go1217jo** [comment]
일단 저도 따로 branch 이어나겠습니다.
그리고 JTextField answer를 public으로 선언해주십시오. KeyAdapter에서 읽어들이는데 좀 필요할 거 같습니다.

**Comment by JeanGyuHu** [comment]
기존에 있던 main 클래스에서 이제 더이상 InputStream 하고 OutputStream 필요 없어보이는데 냅둬야되나요??

**Comment by go1217jo** [comment]
없어져도 될 거 같습니다

**Comment by go1217jo** [comment]
@JeanGyuHu 님 branch에서 가져와 GamePanel 수정 후 gui branch에 업데이트했습니다.

**Comment by go1217jo** [comment]
버튼을 눌러도 panel이 안 떠서 어떤 구성으로 호출해야 하는지 몰라서 commit했습니다.

**Comment by JeanGyuHu** [comment]
확인해보고 수정 후 다시 commit 하도록 하겠습니다.

**Comment by go1217jo** [comment]
GamePanel에서 그림은 어떻게 하실건가요?
애니메이션으로 구현하나요?

**Comment by JeanGyuHu** [comment]
그건 다른 분들의 의견도 다 들어보고 해보죠!

**Comment by go1217jo** [comment]
@JeanGyuHu 이미지 업뎃한 거 그림파일 보내주세요~

**Comment by JeanGyuHu** [comment]
[Images.zip](https://github.com/GradeScholarship/hangman/files/1535463/Images.zip)
이미지 파일 Zip 파일 올려드릴게요!
