### ISSUE TITLE
HangMan 게임 앞으로 진행 방향에 대해서

### ISSUE THREAD

**Issue by JeanGyuHu** [GradeScholarship/hangman#3]
현재 HangMan 게임은 콘솔 기반으로 제작 되어 있고, 영어로 제작 되어있으니
GUI를 사용하여 2개의 페이지로 만들면 좋을 것 같습니다.
프로그램을 시작했을때 첫 화면에서
1. 게임 시작 버튼
2. 도움말 버튼(게임 하는법)
을 만들고
두번째 화면에서 게임을 추가하면 될 것 같습니다.
게임을 끝났을 시에는 게임을 더할것인지 아님 게임을 종료할 것인지 물어보는 Dialog창을 띄워서
예 아니오에 대해서 동작하면 될 것 같습니다.
이에 대해서 다른 분들의 의견 부탁드리겠습니다~

**Comment by go1217jo** [comment]
예, 좋습니다
Merge를 원활하게 하기 위해 panel로 제작 중인데
형이 만든 Frame에서 이 panel을 실행시킬 때 new Main(System.in, System.out, 5).exec(); 와 같이
호출해주셔야 합니다.

**Comment by dovigod** [comment]
문제로 나올 경우의 수가 너무 적어서 몇개만 더 추가할께요~

**Comment by JeanGyuHu** [comment]
좋은 의견입니다!

**Comment by kimhono97** [comment]
@dovigod 단어를 doviii branch의 Main.java에 따로 추가한건가요?
음.. 아예 출제단어.txt를 만들어서 읽어오는 형태로 해도 좋을 것 같습니다.
그렇게 하면 출제단어만을 용이하게 편집할 수도 있고, Merge도 편할 것 같습니다.

**Comment by JeanGyuHu** [comment]
그럼 파일 입출력 부분 @kimhono97 씨가 해주시겠어요??

**Comment by kimhono97** [comment]
음..... 하려는데, String[] WORDS가 여러군데 있어서.. 어디다 해야하는 건지 모르겠네요...;;
Main.java인지 GamePannel.java 인지..
또, 프로그램 흐름이 어디서 어디로 가는지 잘 모르겠어요... 몇년간 Java를 안해서;;

**Comment by JeanGyuHu** [comment]
Main.java는 원작자가 만들던 콘솔 기반의 게임 그대로구요
GUI Branch 안의 src에 있는 7개의 .java 파일이 저희가 만들고 있는 프로그램이에요
거기서 GamePanel에서 손보시면 됩니다 흐름은 이런 형태입니다.
![image](https://user-images.githubusercontent.com/32431385/33514412-ef782bb0-d796-11e7-8956-d9dad9f46559.png)

**Comment by go1217jo** [comment]
와 보기 좋게 잘 정리해주셨네요 대단합니다

**Comment by go1217jo** [comment]
그럼 헌호 씨가 파일처리 브랜치 부분을 만들어서 나중에  
merge 하는걸로 가도 좋겠네요

**Comment by kimhono97** [comment]
gui에서 FIO 브랜치를 분기해서 GamePanel에 파일을 읽도록 수정 후 push했습니다.

단어 파일은 `src\Words.txt` 이고
함수 `ArrayList<String> readFile()`를 만들어서
run() 맨 처음에 ArrayList<String> Words으로 받도록,
그리고 String words가 Words중에서 랜덤으로 받도록 수정했습니다.

**Comment by go1217jo** [comment]
일단 FIO가 다 되었으니 gui branch에 merge하여 계속 수정토록 하겠습니다.
