### ISSUE TITLE
exec() problem

### ISSUE THREAD

**Issue by go1217jo** [GradeScholarship/hangman#4]
exec() 함수를 실행시켜야 게임이 동작하는데 어디에 넣든간에 exec() 함수가 실행되면 멈춰버리는 현상이 있습니다. 따라서 이것을 thread로 구현해야 할 것 같습니다.

**Comment by go1217jo** [comment]
Runnable interface를 GamePanel 클래스에 implements해서 visible(true)가 될 때 run()을 호출하는 방식으로 수정해봤는데 똑같이 멈춰버리네요

**Comment by go1217jo** [comment]
GamePanel 안에 있는 while(true)문이 문제가 되는 것 같은데 이걸 어떻게 대체하면 좋을지 모르겠네요
@kimhono97 한 번 봐주시겠어요?

**Comment by go1217jo** [comment]
일단 Thread로 바꿔놓고 문제되는 부분 주석 처리 해놓았습니다.

**Comment by go1217jo** [comment]
Thread 문제는 해결했지만 입력하는 부분에서 문제가 남았습니다.

**Comment by JeanGyuHu** [comment]
확인해보도록 하겠습니다.

**Comment by go1217jo** [comment]
현재 이벤트 부분에서 반복문이 처리되도록 수정 중 입니다.

**Comment by go1217jo** [comment]
키 이벤트 처리에 일부를 포함시킴으로써 해결되었습니다.
